[build]
  command = "ng build --configuration production"
  publish = "dist"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200