name: Angular CI/CD

on:
  push:
    branches:
      - production # Trigger on push to the production branch
  pull_request:
    branches:
      - production # Trigger on pull request to the production branch

jobs:
  build:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Check out the repository
        with:
          token: ${{ secrets.PAT }} # Use the PAT for checkout

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Set up Node.js environment
        with:
          node-version: "22" # Choose the Node.js version (ensure it's compatible with Angular)

      - name: Install dependencies
        run: |
          npm install  # Install Angular app dependencies

      - name: Build the Angular app
        run: |
          npm run build --configuration=production  # Build the Angular app in production mode

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4 # Action for deploying to GitHub Pages
        with:
          branch: gh-pages # The branch where the app will be deployed
          folder: dist/portfolio # The folder containing the build output (adjust for your project name)
          token: ${{ secrets.PAT }} # Use the PAT for deployment
